services:
  backend:
    build: ./app
    ports:
    - 5001:5001
    container_name: app
    volumes:
      - ./app:/app
  # DataStax Enterprise
  dse:
    image: datastax/dse-server:6.0.2
    container_name: cassandra_db
    command: [ -s ]
    ports:
    - "9042:9042" # cassandra
    environment:
      DS_LICENSE: accept
    volumes:
    - "./cassandra/data:/var/lib/cassandra"
    # Allow DSE to lock memory with mlock
    cap_add:
    - IPC_LOCK
    ulimits:
      memlock: -1
# One instance of DataStax Studio
  studio:
    image: datastax/dse-studio:6.0.0
    container_name: cassandra_studio
    ports:
    # The Web UI exposed to our host
    - "9091:9091"
    depends_on:
    - dse
    environment:
      DS_LICENSE: accept
    volumes:
    - "./cassandra/notebooks:/var/lib/datastax-studio"